version: '3.4'

services:
  queuemasstransit.consumer:
    image: ${DOCKER_REGISTRY-}queuemasstransitconsumer
    build:
      context: .
      dockerfile: QueueMassTransit.Consumer/Dockerfile

  queuemasstransit.sender:
    image: ${DOCKER_REGISTRY-}queuemasstransitsender
    build:
      context: .
      dockerfile: QueueMassTransit/Dockerfile

  myrabbit:
    image: rabbitmq:3.10.7-management
    hostname: myrabbit
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - 15672:15672
      - 5672:5672